#!/bin/bash

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
SETTINGS="$SCRIPT_DIR/../settings.toml"

if [ ! -f "$SETTINGS" ]; then
    echo "ERROR: settings.toml not found. Copy settings.toml.example to Docker/settings.toml and configure." >&2
    exit 1
fi

NETWORK=${NETWORK:-"grouch"}
IMAGE="$NETWORK/app"

HTTP_PORT=${HTTP_PORT:-8080}
GIT_HASH=${GIT_HASH:-$(git -C ../.. rev-parse --short HEAD 2>/dev/null || echo "dev")}
BUILD_DATE=$(date -u +%Y-%m-%d)

# Parse CouchDB connection details from local.ini — single source of truth
LOCAL_INI="$SCRIPT_DIR/../couchdb/etc/local.ini"
ADMIN_LINE=$(grep -A50 '^\[admins\]' "$LOCAL_INI" | grep -m1 '^[^;[ ]')
COUCHDB_ADMIN_USER=$(echo "$ADMIN_LINE" | cut -d= -f1 | tr -d ' ')
COUCHDB_ADMIN_PASSWORD=$(echo "$ADMIN_LINE" | cut -d= -f2- | tr -d ' ')
COUCHDB_PORT=$(grep -A20 '^\[chttpd\]' "$LOCAL_INI" | grep -m1 '^port' | cut -d= -f2 | tr -d ' ')
COUCHDB_PORT=${COUCHDB_PORT:-5984}
COUCHDB_HOSTNAME="couchdb.$NETWORK"

# Use SECRET_KEY from settings.toml if present (uncommented); otherwise generate one
SECRET_KEY=$(grep '^SECRET_KEY' "$SETTINGS" | cut -d= -f2- | tr -d ' "' | head -1)
if [ -z "$SECRET_KEY" ]; then
    SECRET_KEY=$(LC_ALL=C tr -dc 'A-Za-z0-9%_+;:,.-' </dev/urandom | head -c 64)
fi

# Parse DOMAIN for CORS auto-configuration
DOMAIN=$(grep '^DOMAIN' "$SETTINGS" | cut -d= -f2- | tr -d ' "' | head -1)

# Generate infrastructure section, then append user settings.
# SECRET_KEY, DOMAIN, and LETSENCRYPT_EMAIL are excluded from the settings.toml
# append: SECRET_KEY is handled above; the others are infrastructure-only.
mkdir -p generated
cat > generated/config.toml << EOF
# Auto-generated by app/build.sh — do not edit directly.
# User settings are in Docker/settings.toml.

DATABASE_NAME = "reader"
DATABASE_HOSTNAME = "$COUCHDB_HOSTNAME"
DATABASE_PORT = "$COUCHDB_PORT"
DATABASE_USERNAME = "$COUCHDB_ADMIN_USER"
DATABASE_PASSWORD = "$COUCHDB_ADMIN_PASSWORD"

REDIS_URL = "redis://redis.$NETWORK:6379/0"

SECRET_KEY = "$SECRET_KEY"

EOF
grep -v -e '^SECRET_KEY' -e '^DOMAIN' -e '^LETSENCRYPT_EMAIL' "$SETTINGS" >> generated/config.toml || true

# If DOMAIN is set, restrict CORS to that origin; otherwise Flask defaults to '*'.
if [ -n "$DOMAIN" ]; then
    printf '\nCORS_ALLOWED_ORIGINS = "https://%s"\n' "$DOMAIN" >> generated/config.toml
fi

# Parse REFRESH_INTERVAL_MINUTES from settings.toml for cron schedule generation
REFRESH_INTERVAL_MINUTES=$(grep '^REFRESH_INTERVAL_MINUTES' "$SETTINGS" | cut -d= -f2- | tr -d ' "' | head -1)
REFRESH_INTERVAL_MINUTES=${REFRESH_INTERVAL_MINUTES:-20}
CRON_SCHEDULE=$(awk -v m="$REFRESH_INTERVAL_MINUTES" 'BEGIN {
    if (m < 60)  { print "*/" m " * * * *" }
    else         { h = int(m / 60); if (h == 1) print "0 * * * *"; else print "0 */" h " * * * *" }
}')
sed "s|\${CRON_SCHEDULE}|$CRON_SCHEDULE|g" \
    etc/cron.tab.template > generated/cron.tab

docker build \
    --build-arg HTTP_PORT=$HTTP_PORT \
    --build-arg GIT_HASH=$GIT_HASH \
    --build-arg BUILD_DATE=$BUILD_DATE \
    -f Dockerfile \
    -t $IMAGE \
    ../.. \
    "$@"
